# data-raw/epigames.R
# Pre-processing script for the EpiGames Raw Dataset
# Issue #75: Extended to include dynamic behavioral attributes (mask, med, quarantine)
#
# Prerequisites:
#   1. Run playground/epigames-stuff/epigames-analysis-copy/extract_dynamic_attrs.py
#      to generate dynamic_attrs_hourly.csv in that same folder.
#   2. Have data-raw/epigames_hourly.rda available (generated by the previous pipeline).
#
# This script is run from the package root directory.

rm(list = ls())

# ---------------------------------------------------------------------------
# 1. Load the base hourly dataset (edgelist + static attributes)
# ---------------------------------------------------------------------------
load("data-raw/epigames_hourly.rda")
# epigames_hourly is a list with $attributes and $edgelist

# ---------------------------------------------------------------------------
# 2. Load the hourly dynamic behavioral attributes produced by Python
# ---------------------------------------------------------------------------
dyn_attrs_path <- "playground/epigames-stuff/epigames-analysis-copy/dynamic_attrs_hourly.csv"

if (!file.exists(dyn_attrs_path)) {
  stop(
    "dynamic_attrs_hourly.csv not found.\n",
    "Please run extract_dynamic_attrs.py first:\n",
    "  cd playground/epigames-stuff/epigames-analysis-copy\n",
    "  source .venv/bin/activate\n",
    "  python3 extract_dynamic_attrs.py"
  )
}

dyn_attrs_hourly <- read.csv(dyn_attrs_path, stringsAsFactors = FALSE)

# Sanity checks
stopifnot(ncol(dyn_attrs_hourly) == 5)              # id, hour, mask, med, quarantine
stopifnot(nrow(dyn_attrs_hourly) == 594 * 339)       # 201,366 rows
stopifnot(all(dyn_attrs_hourly$id  %in% 1:594))
stopifnot(all(dyn_attrs_hourly$hour %in% 0:338))

cat("Dynamic attrs loaded:", nrow(dyn_attrs_hourly), "rows,",
    ncol(dyn_attrs_hourly), "cols\n")
cat("  Nodes wearing mask (ever):", 
    length(unique(dyn_attrs_hourly$id[dyn_attrs_hourly$mask == 1])), "\n")
cat("  Nodes in quarantine (ever):", 
    length(unique(dyn_attrs_hourly$id[dyn_attrs_hourly$quarantine == 1])), "\n")

# ---------------------------------------------------------------------------
# 3. Bundle into the epigames list (3 elements)
# ---------------------------------------------------------------------------
epigames <- list(
  attributes = epigames_hourly$attributes,   # static, 594 x 6
  edgelist   = epigames_hourly$edgelist,     # hourly, ~39k rows
  dyn_attrs  = dyn_attrs_hourly              # NEW: 201,366 rows (long format)
)

cat("\nepigames list structure:\n")
cat("  $attributes:", nrow(epigames$attributes), "rows x", ncol(epigames$attributes), "cols\n")
cat("  $edgelist:  ", nrow(epigames$edgelist),   "rows x", ncol(epigames$edgelist),   "cols\n")
cat("  $dyn_attrs: ", nrow(epigames$dyn_attrs),  "rows x", ncol(epigames$dyn_attrs),  "cols\n")

# ---------------------------------------------------------------------------
# 4. Save compressed .rda
# ---------------------------------------------------------------------------
usethis::use_data(epigames, overwrite = TRUE, compress = "xz")
cat("\nSaved: data/epigames.rda\n")
