---
title: "netdiffuseR package"
author:
  - George Vega Yon
  - Stephanie Dyal
  - Tim Hayes
  - Thomas Valente
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{netdiffuseR package}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# `diffnet-class` 

## `as_netdiff` function

The advantage of using this function is that, besides of been able to use the different methods for data visualization such as `plot.netdiff`, `heatgraph.netdiff`, `plot_threshold.netdiff`, etc., provides data check before use, in particular:

- Verifies whether the length of the `times` vector (times of adoption) coincides with the number of vertices on the graph
- Recodes the vertices ids so it can be used directly with the package's function without errors.

## Class contents

For a given graph with $n$ individuals in a network with $T$ time periods, the `netdiff-class` consists on the following list of objects:

Object  | Description
------- | -------
 `graph` | A dynamic graph defined as list of length $T$ and $n\times n$ adjacency matrices (class `dgCMatrix`). 
 `adopt` | An $n\times T$ matrix where its elements $\{a_{it}\}$ are equal to one iff $i$ adopted the innovation at time $t$, and zero otherwise (see `toa_mat`)
 `cumadopt`| An $n\times T$ matrix where its elements $\{a_{it}\}$ are equal to one iff $i$ adopted the innovation prior to time $t$, and to zero otherwise (see `toa_mat`).
 `toa` | An integer vector of size $n$ with values going from one to $T$ indicating the _Time of Adoption_ of the innovation for each individual in the network.

## Class methods

Method | Description
-------|------------
`plot` | As many graphs as time periods are, it shows the structure of the network and the set of adopters through time
`heatgraph` | A unique graph coloring vertices according to the time of adoption
`plot_threshold` | Showing threshold through time
`plot_infectsuscep` | A heatmap comparing infectiousness and susceptibility
`infect`  | Calculate infection
`suscept` | Calculate susceptibility
