---
title: |
  | Understanding Diffusion with __netdiffuseR__
  | _More on model estimation_
subtitle: Sunbelt 2016 INSNA
author: George Vega Yon, Stephani Dyal, Timothy Hayes, Thomas Valente
date: |
  | Newport Beach, CA
  | March 28, 2016
institute: |
  | Department of Preventive Medicine
  | University of Southern California
header-includes: \usepackage{grffile}
output: pdf_document
fontsize: 10pt
---

```{r}
library(netdiffuseR)
data("medInnovationsDiffNet")

# Exposure terms

# Structural equivalence
medInnovationsDiffNet[["seexp"]] <- exposure(
  medInnovationsDiffNet, alt.graph = "se", groupvar="city",
  valued = TRUE
)

# Cohesive
medInnovationsDiffNet[["cohexp"]] <- exposure(medInnovationsDiffNet)

# Attribute weighted
medInnovationsDiffNet[["proage"]][is.na(medInnovationsDiffNet[["proage"]])] <- 0
medInnovationsDiffNet[["cohexp_proage"]] <- exposure(
  medInnovationsDiffNet, attrs="proage", groupvar = "city")

# Creating model
dat <- diffnet.attrs(medInnovationsDiffNet, as.df = TRUE)
dat <- subset(
  dat, per <= toa,
  select=c(id, toa, per, city, attend, 
           cohexp, cohexp_proage, seexp, proage))

dat$adopted <- with(dat, per == toa)

mod <- formula(adopted ~ factor(city) + cohexp + cohexp_proage + seexp + I(proage^2) +
      attend*proage)
out <- glm(mod, data=dat, family=binomial(link="logit"))

pander::pander(out)

# Likelihood ratio test
# l0 <- update(out, adopted~1)
# library(rms)
# lrm(mod)
```

# Computing xxx early adopters, laggards

```{r}

sdclass <- function(x, na.rm=TRUE, breaks=c(-1.5,-1,0,1,1.5)) {
  # Computing sd
  x_sd <- sd(x, na.rm = na.rm)
  
  # Creating labels
  m <- length(breaks)
  
  # Computing breaks and classifying
  x_sd <- mean(x, na.rm=na.rm) + x_sd*breaks
  lab <- c(
    sprintf("(-Inf; %.2f)", x_sd[1]),
    sprintf("[%.2f; %.2f)", x_sd[-m], x_sd[-1]),
    sprintf("[%.2f; +Inf)", x_sd[m])
    )
  
  x <- rowSums(sapply(x_sd, `<`, x))
  x[x==0] <- m + 1
  factor(lab[x+1], lab)
}

x <- sdclass(diffnet.toa(medInnovationsDiffNet))
y <- sdclass(threshold(medInnovationsDiffNet))
```


```{r, echo=FALSE, size="\\footnotesize"}
library(pander)
panderOptions("table.split.table",1e3)
pander(table(`Time of Adoption` = x, `Threshold`=y))

```

