FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Architecture-specific variable (built in Docker BuildKit)
ARG TARGETARCH

# Install quarto-cli and the orange-book extension
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.35/quarto-1.9.35-linux-${TARGETARCH}.deb && \
    dpkg -i quarto-1.9.35-linux-${TARGETARCH}.deb && \
    rm quarto-1.9.35-linux-${TARGETARCH}.deb

RUN apt-get update && apt-get install --no-install-recommends -y valgrind gdb \
  libglpk-dev

# Adding R packages
RUN install2.r --error -n4 Rcpp sna network networkDynamic Matrix MASS \
  MatchIt SparseM igraph \
  viridisLite covr testthat knitr rmarkdown ape RSiena survival \
  RcppArmadillo

CMD ["bash"]
