# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

toa_mat_cpp <- function(year) {
    .Call('netdiffuseR_toa_mat_cpp', PACKAGE = 'netdiffuseR', year)
}

edgelist_to_adjmat_cpp <- function(edgelist, weights = as.numeric( c()), n = 0L, undirected = FALSE) {
    .Call('netdiffuseR_edgelist_to_adjmat_cpp', PACKAGE = 'netdiffuseR', edgelist, weights, n, undirected)
}

adjmat_to_edgelist_cpp <- function(adjmat, undirected = TRUE) {
    .Call('netdiffuseR_adjmat_to_edgelist_cpp', PACKAGE = 'netdiffuseR', adjmat, undirected)
}

adjmat_to_dyn_edgelist_cpp <- function(adjmat, undirected = TRUE) {
    .Call('netdiffuseR_adjmat_to_dyn_edgelist_cpp', PACKAGE = 'netdiffuseR', adjmat, undirected)
}

toa_diff_cpp <- function(year) {
    .Call('netdiffuseR_toa_diff_cpp', PACKAGE = 'netdiffuseR', year)
}

isolated_cpp <- function(adjmat, undirected = TRUE) {
    .Call('netdiffuseR_isolated_cpp', PACKAGE = 'netdiffuseR', adjmat, undirected)
}

drop_isolated_cpp <- function(adjmat, isolated, undirected = TRUE) {
    .Call('netdiffuseR_drop_isolated_cpp', PACKAGE = 'netdiffuseR', adjmat, isolated, undirected)
}

infection_cpp <- function(graph, times, normalize = TRUE, K = 1L, r = 0.5, expdiscount = FALSE) {
    .Call('netdiffuseR_infection_cpp', PACKAGE = 'netdiffuseR', graph, times, normalize, K, r, expdiscount)
}

susceptibility_cpp <- function(graph, times, normalize = TRUE, K = 1L, r = 0.5, expdiscount = FALSE) {
    .Call('netdiffuseR_susceptibility_cpp', PACKAGE = 'netdiffuseR', graph, times, normalize, K, r, expdiscount)
}

seq_cpp <- function(from, to, lengthout) {
    .Call('netdiffuseR_seq_cpp', PACKAGE = 'netdiffuseR', from, to, lengthout)
}

#' Distribution over a grid
#'
#' Distribution of pairs over a grid of fix size (number of elements)
#'
#' @param x Numeric vector of size \eqn{n}
#' @param y Numeric vector of size \eqn{n}
#' @param nlevels Integer scalar. Number of bins to return
#' @details
#'
#' This function ment for internal use only.
#'
#' @export
#' @keywords misc
#' @seealso Used by \code{\link{plot_infectsuscep}}
#' @return Returns a list with three elements
#' \item{x}{Numeric vector of size \code{nlevels} with the class marks for x}
#' \item{y}{Numeric vector of size \code{nlevels} with the class marks for y}
#' \item{z}{Numeric matrix of size \code{nlevels} by \code{nlevels} with the distribution %
#' of the elements in terms of frecuency}
#' @section Examples:
#' \code{# Generating random vectors of size 100}
#'
#' \code{x <- rnorm(100)}
#'
#' \code{y <- rnorm(100)}
#'
#' \code{# Calculating distribution}
#'
#' \code{grid_distribution(x,y,20)}
grid_distribution <- function(x, y, nlevels = 100L) {
    .Call('netdiffuseR_grid_distribution', PACKAGE = 'netdiffuseR', x, y, nlevels)
}

edges_coords <- function(graph, toa, x, y, vertex_cex, undirected = TRUE, no_contemporary = TRUE) {
    .Call('netdiffuseR_edges_coords', PACKAGE = 'netdiffuseR', graph, toa, x, y, vertex_cex, undirected, no_contemporary)
}

rand_graph_cpp <- function(n = 10L, p = 0.3, undirected = TRUE, weighted = FALSE, self = FALSE) {
    .Call('netdiffuseR_rand_graph_cpp', PACKAGE = 'netdiffuseR', n, p, undirected, weighted, self)
}

rand_dyn_graph_cpp <- function(n = 10L, t = 3L, p = 0.3, undirected = TRUE, weighted = FALSE, self = FALSE) {
    .Call('netdiffuseR_rand_dyn_graph_cpp', PACKAGE = 'netdiffuseR', n, t, p, undirected, weighted, self)
}

select_egoalter_cpp <- function(adjmat_t0, adjmat_t1, adopt_t0, adopt_t1) {
    .Call('netdiffuseR_select_egoalter_cpp', PACKAGE = 'netdiffuseR', adjmat_t0, adjmat_t1, adopt_t0, adopt_t1)
}

degree_cpp <- function(adjmat, cmode = 2L, undirected = TRUE, self = FALSE) {
    .Call('netdiffuseR_degree_cpp', PACKAGE = 'netdiffuseR', adjmat, cmode, undirected, self)
}

exposure_cpp <- function(graph, cumadopt, wtype = 0L, v = 1.0, undirected = TRUE, normalized = TRUE) {
    .Call('netdiffuseR_exposure_cpp', PACKAGE = 'netdiffuseR', graph, cumadopt, wtype, v, undirected, normalized)
}

cumulative_adopt_count_cpp <- function(cumadopt) {
    .Call('netdiffuseR_cumulative_adopt_count_cpp', PACKAGE = 'netdiffuseR', cumadopt)
}

hazard_rate_cpp <- function(cumadopt) {
    .Call('netdiffuseR_hazard_rate_cpp', PACKAGE = 'netdiffuseR', cumadopt)
}

threshold_cpp <- function(exposure, times) {
    .Call('netdiffuseR_threshold_cpp', PACKAGE = 'netdiffuseR', exposure, times)
}

struct_equiv_cpp <- function(gdist, v = 1.0, unscaled = FALSE, inv = FALSE, invrep = 0.0) {
    .Call('netdiffuseR_struct_equiv_cpp', PACKAGE = 'netdiffuseR', gdist, v, unscaled, inv, invrep)
}

